### ISSUE TITLE
Add Parse function with byte parameter

### ISSUE THREAD

**Issue by ChielTimmermans** [oklog/ulid#68]
Is it possible to add a ParseByte function. 
`
func Parse(ulid []byte) (id ULID, err error) {
	return id, parse(ulid, false, &id)
}
`

Because i get my data as a byte array and have to cast it to string and then this function recast is to a byte array again.

If you want this i can also create a PR with this added function

**Comment by peterbourgon** [comment]
If you have a `[]byte` that's supposed to represent a ULID, you shouldn't need to parse it — a ULID is a `[16]byte` by definition, so you should just be able to cast it.

Where is this `[]byte` coming from and what encoding does it have? Are you saying it's a `[]byte(ulid.String())`?

**Comment by ChielTimmermans** [comment]
The byte array is coming from my front end. It is indeed a []byte(ulid.String()). Im using fasthttp and this library returns all parameters on an url as byte array

**Comment by peterbourgon** [comment]
> I'm using fasthttp 

:( Too bad. You should move away from that package.

No, you should do the conversion yourself. If we added such a function to the package it would just be doing the same thing.

**Comment by ChielTimmermans** [comment]
Can you elaborate why I should move from that library? 

Pretty strange what you are saying. It is definitely not doing the same!? I'm kidding confused by your comment

**Comment by peterbourgon** [comment]
> Can you elaborate why I should move from that library?

fasthttp doesn't implement HTTP, but rather a subset of it, and doesn't implement HTTP/2. It's also just poorly written. It's a niche tool that's ultimately a performance optimization for specific scenarios, not something you should choose by default because you believe net/http is "too slow" (it isn't).

> It is definitely not doing the same!?

A ULID is `[16]byte`, so if you have a `[]byte` which represents a ULID, it should just be those 16 bytes directly. If you have a `[]byte` which is actually the base32 encoded form of a ULID, then you have done something wrong :) as there is no reason for the base32 encoded form of a ULID to be represented anywhere as a `[]byte`, it should always be a `string`.

This is all kind of moot, though. If you're just trying to avoid the conversions, you can use [UnmarshalText](https://pkg.go.dev/github.com/oklog/ulid#ULID.UnmarshalText).

```go
var id ulid.ULID
err := id.UnmarshalText(b)
// handle err
```
