### ISSUE TITLE
Maybe a bad example in the README?

### ISSUE THREAD

**Issue by jasonish** [oklog/ulid#8]
I'm not a big fan of the example in the README.  If the same code block is execute 2x, the ID generated is the same. Perhaps an example that generates something more unique would be better?

**Comment by tsenart** [comment]
The code in this example does both instantiation of the entropy source and ULID generation. Only the former is to be called repeatedly, hence reusing the same instance of entropy (PNRG).

**Comment by jasonish** [comment]
Ok, that makes sense.  However in my use case I have multiple go routines, and it is possible, I think that they could be seeded with the same value? I assume IDs to events, and from the same event source I could have several for the exact same timestamp. I assume, in the ultra-paranoid case of a collision I could seed with an Int64 from crypto/rand?

**Comment by tsenart** [comment]
If the performance hit induced by lock contention in the global package level PNRG in math/rand isn't an issue for you, use that.

Using crypto/rand also incurs a significant cost (as shown in the benchmarks) due to the dependent syscall.

If you want to have an entropy source per long living go-routine, as to avoid the above, I'd seed them from a single timestamp, incremented by one for each go-routine.

**Comment by jasonish** [comment]
Thanks for the input!
